extends: eslint:recommended

env:
  node: true
  es2020: true

parserOptions:
  ecmaVersion: 2020

rules:
  no-constant-condition:
    - error
    - checkLoops: false
  no-unused-vars:
    - error
    - varsIgnorePattern: ^_
      argsIgnorePattern: ^_
